name: update resources
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */1 * * *'
  
  workflow_dispatch:

jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            
            - name: Fetch resources
              run: python3 championrate.py

            - name: Update resources
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: riot/lol/resources/latest/en-US/championrates.json
                  commit-msg: Update resources
                  github-token: ${{ secrets.GITHUB_TOKEN }}
